### ISSUE TITLE
Unable to start the plugin 

### ISSUE THREAD

**Issue by kelvinyasu** [sahilchaddha/homebridge-yeelight-platform#12]
```
Load homebridge-yeelight-platform.Yeelight-Platform

/homebridge/node_modules/homebridge-yeelight-platform/src/yeelight.js:22
  this.debug = this.config.debug || false
                           ^
TypeError: Cannot read property 'debug' of null
    at new YeelightPlatform (/homebridge/node_modules/homebridge-yeelight-platform/src/yeelight.js:22:28)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:347:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:88:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
Starting homebridge in debug mode...
-U /homebridge -P /homebridge/node_modules -C -D

```

I am running with Raspberry Pi with docker image for homebridge... Version 0.4.45

**Comment by sahilchaddha** [comment]
@kelvinyasu , Kindly add this to your config.json

```
{
  "platform": "Yeelight-Platform",
  "addResetSwitch": false,
  "scenes": []
}
```

**Comment by kelvinyasu** [comment]
Thanks, it works... some mis-configuration before :)
