### ISSUE TITLE
Can't start on my router (openwrt latest version)

### ISSUE THREAD

**Issue by Release-Pre-1668** [sahilchaddha/homebridge-yeelight-platform#20]
### Log:
```
[Sun Jul 14 2019 20:58:31 GMT+0800 (CST)] [homebridge-yeelight.yeelight] DidFinishLaunching
[Sun Jul 14 2019 20:58:31 GMT+0800 (CST)] [homebridge-yeelight.yeelight] no ble cap, skip ble device discovery
[Sun Jul 14 2019 20:58:31 GMT+0800 (CST)] Homebridge is running on port 8888.
[Sun Jul 14 2019 20:58:31 GMT+0800 (CST)] Error: bind EADDRINUSE 0.0.0.0:1982
    at _handle.lookup (dgram.js:266:18)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
[Sun Jul 14 2019 20:58:31 GMT+0800 (CST)] Got SIGTERM, shutting down Homebridge...
```
I think that is bind ip issue, but the config.json no any settings about this.
Thanks!

**Comment by sahilchaddha** [comment]
Your port is already in use. You need to make sure no other application/homebridge instance is using this port.
